apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: bookinfo
  labels:
    app: jaeger
    service: jaeger
spec:
  selector:
    app: jaeger
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger-v1
  namespace: bookinfo
  labels:
    app: jaeger
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
      version: v1
  template:
    metadata:
      labels:
        app: jaeger
        version: v1
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 16686
          name: ui
        - containerPort: 4317
          name: otlp-grpc